container:
    backend: docker
    singularity_path: /opt/singularity-2.5.2/bin/singularity
    udocker_path: udocker
    singularity_image: /home/vbox/singularity/exseek2
    docker_image: ltbyshi/exseek
    wrapper_dir: singularity/wrappers
data_dir: data/cfRNA_small
output_dir: output/cfRNA_small
threads: 4
star_genome_generate:
  sjdbOverhang: 100
  limitGenomeGenerateRAM: 16000000000
adaptor: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
paired_end: false
small_rna: true
imputation_method: ["null"]
# Read depth normalization methods to try
normalization_method: ["TMM"]
# Batch effect removal methods to try (set "null" to skip batch effect removal)
batch_removal_method: ["null"]
