container:
    backend: singularity
    singularity_path: /opt/singularity-2.5.2/bin/singularity
    udocker_path: udocker
    singularity_image: /home/vbox/singularity/exseek2
    wrapper_dir: singularity/wrappers
data_dir: data/example_small
aligner: bowtie2
adaptor: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
paired_end: false
# Discard reads of length below this value
min_read_length: 16
small_rna: true
